export enum ERROR_NAME {
  USER_NOT_FOUND_ERROR = 'UserNotFoundError',
  GENERATE_ID_ERROR = 'GenerateIDError',
  INVALID_ID_ERROR = 'InvalidIDError',
  INTERNAL_ERROR = 'InternalError',
  INVALID_EMAIL_ERROR = 'InvalidEmailError',
  INVALID_PASSWORD_FORMAT_ERROR = 'InvalidPasswordFormatError',
  INVALID_PASSWORD_LENGTH_ERROR = 'InvalidPasswordLengthError',
  INVALID_WHATSAPP_ERROR = 'InvalidWhatsappError',
  INVALID_CUSTOMER_NAME_ERROR = 'InvalidCustomerNameError',
  INVALID_RESTAURANT_OWNER_NAME_ERROR = 'InvalidRestaurantOwnerNameError',
  REPOSITORY_ERROR = 'RepositoryError',
  PROVIDER_ERROR = 'ProviderError',
  UNKNOWN_EVENT_CONTRACT_NAME_ERROR = 'UnknownEventContractNameError',
  WHATSAPP_ALREADY_IN_USE_ERROR = 'WhatsappAlreadyInUseError',
  EMAIL_ALREADY_IN_USE_ERROR = 'EmailAlreadyInUseError',
  INVALID_DATETIME_ERROR = 'InvalidDateTimeError',
  DATETIME_OUT_OF_RANGE_ERROR = 'DateTimeOutOfRangeError',
  INVALID_DAY_OF_WEEK_ERROR = 'InvalidDayOfWeekError',
  INVALID_MONTH_OF_YEAR_ERROR = 'InvalidMonthOfYearError'
}
